name: "Weather Cronjob"
on:
  schedule:
    # - cron: "15 * * * *"
    - cron: "*/5 * * * *"

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate README
        uses: huantt/weather-forecast@v1.0.5
        with:
          city: Manila
          days: 7
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
          template-file: "README.md.template"
          out-file: "README.md"
      - name: Commit
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git config user.name Robbie Mariano
            git config user.email robbiemariano126@gmail.com
            git add .
            git commit -m "update"
            git push origin main
          fi
